services:
  - type: web
    name: ANJAN-XD
    env: node
    branch: main
    repo: https://github.com/Anjan-Ser/ANJAN-XD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: â˜…ğ€ğğ‰ğ€ğ-ğ—ğƒâ˜…;â˜…ğ€ğğ‰ğ€ğ-ğ—ğƒâ˜…;https://telegra.ph/file/0c7a2c47fa748d97402c8.jpg
      - key: ALWAYS_ONLINE
        value: true
      - key: AUTO_STATUS_VIEWS
        value: true
      - key: AUDIO_DATA
        value: â˜…ğ€ğğ‰ğ€ğ-ğ—ğƒâ˜…;â˜…ğ€ğğ‰ğ€ğ-ğ—ğƒâ˜…;https://telegra.ph/file/0c7a2c47fa748d97402c8.jpg
      - key: PREFIX
        value: ^
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: CAPTION
        value: â˜…ğ€ğğ‰ğ€ğ-ğ—ğƒâ˜…
      - key: STICKER_DATA
        value: â˜…ğ€ğğ‰ğ€ğ-ğ—ğƒâ˜…
      - key: SUDO
        value: 919883457657
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
      - key: LOGS
        value: true
